### ISSUE TITLE
Threshold of niche and popular items.

### ISSUE THREAD

**Issue by LiuJiXiong** [ash-shar/Long-Tail-GAN#1]
Hello, would you mind telling me some suggestions ahout how to determine the **threshold** while seperating the niche and popular items?

**Comment by ash-shar** [comment]
In general, one can use the distribution of the item usage frequency to decide a threshold for separating popular and niche items. However, picking an optimum threshold is a hard problem. One can pick the top-k items that contribute to a large number of data points as popular items. The value of k can be approximated based on the distribution and the dataset. Another strategy could be to always select the top x% items as popular items (and the rest as niche).

**Comment by LiuJiXiong** [comment]
Thanks, I pretty think so. And I also find the strategy that many researcher select the top x% items as the popular items(and the rest as niche).
